export const ADD_FEATURE = "ADD_FEATURE"
export const REMOVE_FEATURE = "REMOVE_FEATURE"

export const ADD_CONTEXT = "ADD_CONTEXT"
export const REMOVE_CONTEXT = "REMOVE_CONTEXT"

export const ADD_EVENT = "ADD_EVENT"
export const REMOVE_EVENT = "REMOVE_EVENT"

export const ADD_SENTENCE = "ADD_SENTENCE"
export const REMOVE_SENTENCE = "REMOVE_SENTENCE"

